variables: private/variables.yml

web_server:
  run_v2: true
  port: '{? port ?}'

templates:
  main:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
        - '*.r0*'
        - '*.rar'
      reject:
        - 'password.txt'
        - '*.wmv'
        - '*CD1*'

  tv:
    trakt_lookup: yes
    if:
      - trakt_ep_first_aired and trakt_ep_first_aired <= now - timedelta(days=2): accept
    set:
      label: tv
      path: /volume1/Media/Videos/To.Watch/TV/{{series_name[:-7].replace(' ', '.')}}/
      content_filename: '{{trakt_ep_id}}.{{trakt_ep_name}}'
      specials: no
      propers: yes
      ratio: 3.0
    include: [private/tvrss.yml]
    html:
      url: https://piratebaymirror.eu/browse/208/{{i}}/3/0
      links_re: [magnet]
      title_from: url
      increment:
        from: 0
        to: 3

  tvBest:
    configure_series:
      settings:
        target: 1080p hdtv+
        quality: <=1080p
        timeframe: 30 minutes
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV Best
          type: shows

  tvBetter:
    configure_series:
      settings:
        target: <=720p webrip+
        quality: <=720p
        timeframe: 30 minutes
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV Better
          type: shows

  tvAVG:
    configure_series:
      settings:
        target: <=720p preair+
        quality: <=720p
        timeframe: 30 minutes
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV Average
          type: shows

  movies:
    proper_movies: yes
    exists_movie:
      - /volume1/Media/Videos/
      - /volume1/Media/Videos/To.Watch/Movies/
    content_size:
      max: 5000
      strict: yes
    set:
      quality: dvdscr+
      target: 720p ac3+
      label: Movies
      path: /volume1/Media/Videos/To.Watch/Movies/
      temp: /volume1/Media/Downloads/
    include: [private/moviesrss.yml]
    html:
      url: https://piratebaymirror.eu/browse/207/{{i}}/3/0
      links_re: [magnet]
      title_from: url
      increment:
        from: 0
        to: 3

  movies-private:
    set:
      ratio: 3.0

  movies-keep:
    set:
      label: keep
      quality: 1080p
    list_match:
      from:
        - movie_list: KEEPERS
      remove_on_match: yes

  movies-watch:
    set:
      label: watch
      quality: r5+
    list_match:
      from:
        - movie_list: WATCH
      remove_on_match: yes

tasks:
  TVBest:
    template:
      - main
      - tv
      - tvBest

  TVBetter:
    template:
      - main
      - tv
      - tvBetter

  TVAVG:
    template:
      - main
      - tv
      - tvAVG

  MoviesKeep:
    template:
      - main
      - movies
      - movies-keep

  MoviesWatch:
    template:
      - main
      - movies
      - movies-watch

  MoviesWatchQueue:
    trakt_list:
      username: lvleph
      account: lvleph
      list: Keepers
      type: movies
    list_add:
      - movie_list: KEEPERS
    accept_all: yes

  MoviesKeepQueue:
    trakt_list:
      username: lvleph
      account: lvleph
      list: watchlist
      type: movies
    list_add:
      - movie_list: WATCH
    accept_all: yes

  RemoveTrakt:
    filesystem:
      path:
        - /volume1/Media/Videos/Movies
        - /volume1/Media/Videos/To.Watch/Movies
      recursive: yes
      retrieve: files
      regexp: '^.*[^sample].*\.(avi|mp4,mkv,m4v)$'
    trakt_lookup: yes
    accept_all: yes
    list_remove:
      - trakt_list:
          username: lvleph
          account: lvleph
          list: Keepers
          type: movies
      - trakt_list:
          username: lvleph
          account: lvleph
          list: watchlist
          type: movies
      - movie_list: WATCH
      - movie_list: KEEPERS

schedules:
  - tasks: [TVBest, TVBetter, TVAVG]
    interval:
      minutes: 15
  - tasks: [MoviesWatch, MoviesKeep]
    interval:
      minutes: 60
  - tasks: [MoviesKeepQueue, MoviesWatchQueue]
    interval:
      hours: 24
  - tasks: RemoveTrakt
    interval:
      weeks: 4
