presets:
  global:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mpg'
        - '*.mp4'
        - '*.r0*'
        - '*.rar'
      reject:
        - 'password.txt'
        - '*.wmv'
    # The Pirate Bay ssl certs always fail
    verify_ssl_certificates: no
    # Size and seed restrictions require real torrents
    magnets: no

  tv:
    include: [series.yml]
    exists_series: 
      - /mnt/usb_storage/USB_DISK0/MediaUSB/Videos/Series/ 
      - /mnt/usb_storage/USB_DISK0/MediaUSB/Videos/Torrents/
      - /mnt/usb_storage/USB_DISK0/MediaUSB/Videos/To.Watch/
    thetvdb_lookup: yes
    if:
      - tvdb_ep_air_date < now - timedelta(days=2): reject
    set:
      label: tv
    series:
      settings:
        Best:
          target: 720p hdtv+
          quality: <=1080p hdtv+
          timeframe: 30 minutes
          propers: no
        Better:
          target: <720p dvdscr+
          quality: <=720p webrip+
          timeframe: 30 minutes
          propers: no
        Avereage:
          target: <720p
          quality: preair+
          timeframe: 30 minutes
          propers: no

  tv-private:
    include: [private/tvrss.yml]
    set:
      ratio: 2.0

  tv-public:
    include: [tvrss.yml]
    set:
      ratio: 0.0

  premieres:
    include: [tvrss.yml]
    series_premiere: yes
    quality: <720p
    regexp:
      reject:
        - game show
        - news
        - sports
        - talk show
      from: tvdb_genres
    if:
      - tvdb_ep_air_date < now - timedelta(days=1): reject
    set:
      label: premiere
      ratio: 0.0

  movies:
    proper_movies: yes
    exists_movie: 
      - /mnt/usb_storage/USB_DISK0/MediaUSB/Videos/
    content_size:
      max: 3500
      strict: yes
    set:
      quality: dvdscr+ 
      target: 720p ac3+  

  movies-keep:
    include: [private/traktKeep.yml]

  movies-watch:
    include: [private/traktWatch.yml]

  movies-private:
    include: [private/moviesrss.yml]
    set: 
      ratio: 2.0

  movies-public:
    include: [moviesrss.yml]
    set: 
      ratio: 0.0

  clean-watch:
    include: [private/cleanWatch.yml]

  clean-keep:
    include: [private/cleanKeep.yml]

tasks:
  TVPublic:
    priority: 1
    preset: 
      - global
      - tv
      - tv-public

  TVPrivate:
    priority: 2
    preset: 
      - global
      - tv
      - tv-private

#  TVPremieres:
#    priority: 99
#    preset: premieres

  MoviesPublic:
    priority: 3
    preset: 
      - global
      - movies
      - movies-public
    movie_queue: yes
    seen: local

  MoviesPrivate:
    priority: 4
    preset: 
      - global
      - movies
      - movies-private
    movie_queue: yes
    seen: local

  MoviesKeep:
    preset: 
      - no_global
      - movies-keep
      - clean-keep
    accept_all: yes
    interval: 1 days
    queue_movies: 
      quality: 720p
      force: no

  MoviesWatch:
    preset: 
      - no_global
      - movies-watch
      - clean-watch
    accept_all: yes
    interval: 1 days
    queue_movies: 
      quality: r5+
      force: no
