templates:
  global:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.r0*'
        - '*.rar'
      reject:
        - 'password.txt'
        - '*.wmv'
        - '*CD1*'
    # The Pirate Bay ssl certs always fail
    verify_ssl_certificates: no
    # Size and seed restrictions require real torrents
    magnets: no
    download: yes

  tv:
    include: [series.yml]
    thetvdb_lookup: yes
    if:
      - tvdb_ep_air_date < now - timedelta(days=2): reject
    set:
      label: tv
      path: ~/To.Watch/TV/
      temp: ~/Downloads/
      specials: no
      propers: yes
    series:
      settings:
        Best:
          target: 720p hdtv+
          quality: <=720p
          timeframe: 30 minutes
        Better:
          target: <=720p webrip+
          quality: <=720p
          timeframe: 30 minutes
        Average:
          target: <=720p preair+
          quality: <=720p
          timeframe: 30 minutes

  tv-private:
    include: [private/tvrss.yml]
    set:
      ratio: 2.0

  tv-public:
    include: [tvrss.yml]
    set:
      ratio: 0.0

  movies:
    proper_movies: yes
    exists_movie:
      - /volume1/Media/Videos
      - /volume1/Media/Videos/To.Watch/Movies/
    content_size:
      max: 3500
      strict: yes
    set:
      quality: dvdscr+
      target: 720p ac3+
      label: Movies
      path: ~/To.Watch/Movies/
      temp: ~/Downloads/

  movies-keep:
    include: [private/traktKeep.yml]
    set:
      label: keep

  movies-watch:
    include: [private/traktWatch.yml]
    set:
      label: watch

  movies-private:
    include: [private/moviesrss.yml]
    set:
      ratio: 2.0

  movies-public:
    include: [moviesrss.yml]
    set:
      ratio: 0.0

  clean-watch:
    include: [private/cleanWatch.yml]

  clean-keep:
    include: [private/cleanKeep.yml]

tasks:
  TVPublic:
    priority: 1
    template:
      - global
      - tv
      - tv-public

  TVPrivate:
    priority: 2
    template:
      - global
      - tv
      - tv-private

  MoviesPublic:
    priority: 3
    template:
      - global
      - movies
      - movies-public
    seen: local

  MoviesPrivate:
    priority: 4
    template:
      - global
      - movies
      - movies-private
    seen: local

  MoviesKeep:
    template:
      - no_global
      - movies-keep
      - clean-keep
    accept_all: yes
    interval: 1 days
    movie_queue:
      action: add
      quality: 720p

  MoviesWatch:
    template:
      - no_global
      - movies-watch
      - clean-watch
    accept_all: yes
    interval: 1 days
    movie_queue:
      action: add
      quality: r5+

  CleanUp:
    include: [private/cleanTransmission.yml, private/cleanKeep.yml, private/cleanWatch.yml]

schedules:
  - tasks: [TVPrivate, TVPublic]
    interval:
      minutes: 15
  - tasks: [MoviesPublic, MoviesPrivate]
    interval:
      minutes: 60
  - tasks: [MoviesKeep, MoviesWatch, CleanUp]
    interval:
      hours: 24
