variables: private/variables.yml

web_server:
  port: '{? port ?}'

schedules:
  - tasks: TV
    interval:
      minutes: 15
  - tasks: [Movies]
    interval:
      minutes: 60
  - tasks: [MoviesQueue]
    interval:
      hours: 24

tasks:
  TV:
    template:
      - main
      - tv

  Movies:
    template:
      - main
      - movies
    exists_movie:
      - /media/NFS/Media-NAS/Videos/Movies/
      - /media/NFS/Media-NAS/Videos/To.Watch/Movies/

  MoviesQueue:
    trakt_list:
      username: lvleph
      account: lvleph
      list: watchlist
      type: movies
    list_add:
      - movie_list: MOVIES
    accept_all: yes

templates:
  main:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
        - \b(HC|hc)\b: {from: title}
        - \b(cam|CAM)\b: {from: title}
        - \b(hdcam|HDCAM)\b: {from: title}
        - \b[Xx]vid: {from: title}
    content_filter:
      require: '*.mkv'
      reject:
        - '*.avi'
        - '*.m4v'
        - '*.mp4'
        - '*.rar'
        - '*.wmv'
        - 'password.txt'
        - '*CD1*'
    set:
      ratio: 3.
    torrent_alive: 1

  tv:
    trakt_lookup: yes
    set:
      label: tv
      path: /media/NFS/Media-NAS/Videos/To.Watch/TV/{{title | re_replace('[sS][0-9]{1,2}[eE][0-9]{1,3}.+', '') | replace('.', ' ') | replace(':', '') | title() | re_replace('[. ]$', '') | replace(' ', '.') }}/
      specials: no
      propers: yes
      upgrade: no
      timeframe: 30 minute
      type: shows
      quality: 720p-1080p hdtv+
    content_size:
      max: 5000
      strict: no
    include: [private/tvrss.yml]
    inputs:
      - html:
          url: https://thepiratebay.org/browse/208/{{i}}/3/0
          links_re: [magnet]
          title_from: url
          increment:
            from: 0
            to: 3
      - rss: https://rarbg.to/rssdd.php?category=18%3B41
    configure_series:
      settings:
        target: 720p-1080p hdtv+
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV
          type: shows

  movies:
    trakt_lookup: yes
    proper_movies: yes
    content_size:
      max: 8000
      strict: no
    set:
      quality: dvdscr+
      target: 720p-1080p ac3+ h264+
      label: Movies
      path: /media/NFS/Media-NAS/Videos/To.Watch/Movies/
    include: [private/moviesrss.yml]
    inputs:
      - html:
          url: https://thepiratebay.org/browse/207/{{i}}/3/0
          links_re: [magnet]
          title_from: url
          increment:
            from: 0
            to: 3
      - rss: https://rarbg.to/rssdd.php?category=17%3B44
    list_match:
      from:
        - movie_list: MOVIES
      remove_on_match: yes
