variables: private/variables.yml

web_server:
  run_v2: true
  port: '{? port ?}'

schedules:
  - tasks: [TVBest, TVBetter, TVAVG]
    interval:
      minutes: 15
  - tasks: [MoviesWatch, MoviesKeep]
    interval:
      minutes: 60
  - tasks: [AVI2MKV, MoviesKeepQueue, MoviesWatchQueue, bakDocs]
    interval:
      hours: 24
  - tasks: [MKVQueue]
    interval:
      weeks: 4

tasks:
  bakDocs:
    exec:
      on_start:
        phase:
          - rsync -Phavz chantelle@'{? rsyncIP ?}':Documents/ /volume1/Media/chantelles.Docs/ &> /var/log/chantelleRsync.log &
          - rsync -Phavz erichlf@'{? rsyncIP ?}':Documents/ /volume1/Media/erichs.Docs/ &> /var/log/erichRsync.log &
    no_entries_ok: yes

  TVBest:
    template:
      - main
      - tv
      - tvBest

  TVBetter:
    template:
      - main
      - tv
      - tvBetter

  TVAVG:
    template:
      - main
      - tv
      - tvAVG

  MoviesKeep:
    template:
      - main
      - movies
      - moviesKeep

  AVI2MKV:
    template:
      - main
      - movies
      - moviesKeep
      - avi2mkv

  MoviesWatch:
    template:
      - main
      - movies
      - moviesWatch

  MoviesWatchQueue:
    template:
      - moviesQueue
    set:
      list: watchlist
      type: movies
    list_add:
      - movie_list: WATCH

  MoviesKeepQueue:
    template:
      - moviesQueue
    set:
      list: Keepers
      type: movies
    list_add:
      - movie_list: KEEPERS

  MKVQueue:
    filesystem:
      path:
        - /volume1/Media/Videos/Movies
      recursive: yes
      retrieve: files
      regexp: '.+\.(avi|mp4|m4v)$'
    accept_all: yes
    trakt_lookup: yes
    list_add:
      - movie_list: AVI2MKV
    seen: local

templates:
  main:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
        - (h|H)264: {from: title}
    content_filter:
      require: '*.mkv'
      reject:
        - '*.avi'
        - '*.m4v'
        - '*.mp4'
        - '*.rar'
        - '*.wmv'
        - 'password.txt'
        - '*CD1*'

  avi2mkv:
    discover:
      what:
        - movie_list: AVI2MKV
      from:
        - torrentday:
            uid: '153593'
            cfduid: '{? tdCFDUID ?}'
            passkey: '{? tdPASSKEY ?}'
            rss_key: '{? tdRSS_KEY ?}'
            category: 11
        - rarbg:
            category: [17, 44, 45]
        - piratebay:
            category: 207
    list_match:
      from:
        - movie_list: AVI2MKV
    seen: local
    limit_new: 5

  tv:
    trakt_lookup: yes
    set:
      label: tv
      path: /volume1/Media/Videos/To.Watch/TV/{{series_name[:-7].replace(' ', '.')}}/
      specials: no
      propers: yes
      ratio: 3.
      upgrade: no
      timeframe: 30 minute
      type: shows
      quality: 720p-1080p
    content_size:
      max: 2600
      strict: no
    include: [private/tvrss.yml]
    inputs:
      - html:
          url: https://thepiratebay.org/browse/208/{{i}}/3/0
          links_re: [magnet]
          title_from: url
          increment:
            from: 0
            to: 3
      - rss: https://rarbg.to/rssdd.php?category=18%3B41

  tvBest:
    configure_series:
      settings:
        target: 720p-1080p hdtv+
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV Best

  tvBetter:
    configure_series:
      settings:
        target: 720p webrip+
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV Better

  tvAVG:
    configure_series:
      settings:
        target: 720p preair+
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV Average

  movies:
    proper_movies: yes
    exists_movie:
      - /volume1/Media/Videos/Movies/
      - /volume1/Media/Videos/To.Watch/Movies/
    content_size:
      max: 8000
      strict: no
    set:
      quality: dvdscr+
      target: 720p-1080p ac3+ h264
      label: Movies
      path: /volume1/Media/Videos/To.Watch/Movies/
      ratio: 2.0
    include: [private/moviesrss.yml]
    inputs:
      - html:
          url: https://thepiratebay.org/browse/207/{{i}}/3/0
          links_re: [magnet]
          title_from: url
          increment:
            from: 0
            to: 3
      - rss: https://rarbg.to/rssdd.php?category=17%3B44

  moviesKeep:
    set:
      label: keep
      quality: 1080p ac3+ h264
      require:
        - '*.mkv'
    list_match:
      from:
        - movie_list: KEEPERS
      remove_on_match: yes

  moviesWatch:
    set:
      label: watch
      quality: 720p-1080p r5+
    list_match:
      from:
        - movie_list: WATCH
      remove_on_match: yes

  moviesQueue:
    trakt_list:
      username: lvleph
      account: lvleph
      list: watchlist
      type: movies
    accept_all: yes

