templates:
  global:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
        - '*.r0*'
        - '*.rar'
      reject:
        - 'password.txt'
        - '*.wmv'
        - '*CD1*'
    # The Pirate Bay ssl certs always fail
    verify_ssl_certificates: yes
    # Size and seed restrictions require real torrents
    magnets: no
    download: yes

  tv:
    include: [series.yml]
    thetvdb_lookup: yes
    if:
      - "tvdb_ep_air_date is not None":
          if:
            - tvdb_ep_air_date < now - timedelta(days=2): reject
    set:
      label: tv
      path: /media/sdal/lvleph/To.Watch/TV/
      temp: /media/sdal/lvleph/Downloads/
      specials: no
      propers: yes
    series:
      settings:
        Best:
          target: 720p hdtv+
          quality: <=720p
          timeframe: 30 minutes
        Better:
          target: <=720p webrip+
          quality: <=720p
          timeframe: 30 minutes
        Average:
          target: <=720p preair+
          quality: <=720p
          timeframe: 30 minutes

  tv-private:
    include: [private/tvrss.yml]
    set:
      ratio: 3.0

  tv-public:
    include: [tvrss.yml]
    set:
      ratio: 1.0

  movies:
    proper_movies: yes
    exists_movie:
      - /volume1/Media/Videos
      - /volume1/Media/Videos/To.Watch/Movies/
    content_size:
      max: 4500
      strict: yes
    set:
      quality: dvdscr+
      target: 720p ac3+
      label: Movies
      path: /media/sdal/lvleph/To.Watch/Movies/
      temp: /media/sdal/lvleph/Downloads/

  movies-private:
    include: [private/moviesrss.yml]
    set:
      ratio: 3.0

  movies-public:
    include: [moviesrss.yml]
    set:
      ratio: 1.0

  movies-keep:
    set:
      label: keep
      quality: 720p+

  movies-watch:
    set:
      label: watch
      quality: r5+

tasks:
  TVPublic:
    priority: 1
    template:
      - global
      - tv
      - tv-public

  TVPrivate:
    priority: 2
    template:
      - global
      - tv
      - tv-private

  MoviesKeepPublic:
    priority: 3
    template:
      - global
      - movies
      - movies-public
      - movies-keep
    seen: local
    list_queue:
      - movie_list: KEEPERS
    list_remove:
      - movie_list: KEEPERS

  MoviesWatchPublic:
    priority: 4
    template:
      - global
      - movies
      - movies-private
      - movies-watch
    seen: local
    list_queue:
      - movie_list: WATCH
    list_remove:
      - movie_list: WATCH

  MoviesKeepPrivate:
    template:
      - global
      - movies
      - movies-private
      - movies-keep
    list_queue:
      - movie_list: KEEPERS
    list_remove:
      - movie_list: KEEPERS

  MoviesWatchPrivate:
    template:
      - global
      - movies
      - movies-private
      - movies-watch
    list_queue:
      - movie_list: WATCH
    list_remove:
      - movie_list: WATCH

  MoviesWatchQueue:
    template:
      - no_global
    trakt_list:
      username: lvleph
      account: lvleph
      list: Keepers
      type: movies
    list_add:
      - movie_list: KEEPERS
    accept_all: yes

  MoviesKeepQueue:
    template:
      - no_global
    trakt_list:
      username: lvleph
      account: lvleph
      list: watchlist
      type: movies
    list_add:
      - movie_list: WATCH
    accept_all: yes

  RemoveTrakt:
    template:
      - no_global
    filesystem: 
      path:
        - /volume1/Media/Videos/Movies
        - /volume1/Media/Videos/To.Watch/Movies
      recursive: yes
      retrieve: files
      regexp: '^.*[^sample].*\.(avi|mp4,mkv,m4v)$'
    imdb_lookup: yes
    accept_all: yes
    list_remove:
      - trakt_list:
          username: lvleph
          account: lvleph
          list: Keepers
          type: movies
      - trakt_list:
          username: lvleph
          account: lvleph
          list: watchlist
          type: movies
      - movie_list: WATCH
      - movie_list: KEEPERS

schedules:
  - tasks: [TVPrivate, TVPublic]
    interval:
      minutes: 15
  - tasks: [MoviesWatchPrivate, MoviesKeepPrivate, MoviesWatchPublic, MoviesKeepPublic]
    interval:
      minutes: 60
  - tasks: [MoviesKeepQueue, MoviesWatchQueue]
    interval:
      hours: 24
  - tasks: RemoveTrakt
    interval:
      weeks: 4
