variables: private/variables.yml

web_server:
  port: '{? port ?}'

schedules:
  - tasks: TV
    interval:
      minutes: 15
  - tasks: [Movies]
    interval:
      minutes: 60
  - tasks: [AVI2MKV, MoviesQueue, bakDocs]
    interval:
      hours: 24
  - tasks: [MKVQueue]
    interval:
      weeks: 4

tasks:
  bakDocs:
    exec:
      on_start:
        phase:
          - echo $(date) >> /var/log/chantelleRsync.log
          - rsync -Phavz -e "ssh -o StrictHostKeyChecking=no" chantelle@{? rsyncIP ?}:Documents/ /share/Public/chantelles.Docs/ &>> /var/log/chantelleRsync.log &
          - echo $(date) >> /var/log/erichRsync.log
          - rsync -Phavz -e "ssh -o StrictHostKeyChecking=no" erichlf@{? rsyncIP ?}:Documents/ /share/Public/erichs.Docs/ &>> /var/log/erichRsync.log &
    no_entries_ok: yes

  TV:
    template:
      - main
      - tv

  AVI2MKV:
    template:
      - main
      - movies
      - avi2mkv

  Movies:
    template:
      - main
      - movies
    exists_movie:
      - /share/Public/Videos/Movies/
      - /share/Public/Videos/To.Watch/Movies/

  MoviesQueue:
    trakt_list:
      username: lvleph
      account: lvleph
      list: watchlist
      type: movies
    list_add:
      - movie_list: MOVIES
    accept_all: yes

  MKVQueue:
    filesystem:
      path:
        - /share/Public/Videos/Movies
      recursive: yes
      retrieve: files
      regexp: '.+\.(avi|mp4|m4v)$'
    accept_all: yes
    trakt_lookup: yes
    list_add:
      - movie_list: AVI2MKV
    seen: local

templates:
  main:
    include: [private/transmission.yml]
    regexp:
      reject:
        - \btrailer\b: {from: title}
        - \b(HC|hc)\b: {from: title}
        - \b(cam|CAM)\b: {from: title}
        - \b(hdcam|HDCAM)\b: {from: title}
        - \b[Xx]vid: {from: title}
    content_filter:
      require: '*.mkv'
      reject:
        - '*.avi'
        - '*.m4v'
        - '*.mp4'
        - '*.rar'
        - '*.wmv'
        - 'password.txt'
        - '*CD1*'
    set:
      ratio: 3.
    torrent_alive: 1

  avi2mkv:
    discover:
      what:
        - movie_list: AVI2MKV
      from:
        - torrentday:
            uid: '153593'
            cfduid: '{? tdCFDUID ?}'
            passkey: '{? tdPASSKEY ?}'
            rss_key: '{? tdRSS_KEY ?}'
            category: 11
      release_estimations: ignore  # because blu-ray.org is screwing this up
    list_match:
      from:
        - movie_list: AVI2MKV
    seen: local
    limit_new: 10

  tv:
    trakt_lookup: yes
    set:
      label: tv
      path: /share/Public/Videos/To.Watch/TV/{{title | re_replace('[sS][0-9]{1,2}[eE][0-9]{1,3}.+', '') | replace('.', ' ') | replace(':', '') | title() | re_replace('[. ]$', '') | replace(' ', '.') }}/
      specials: no
      propers: yes
      upgrade: no
      timeframe: 30 minute
      type: shows
      quality: 720p-1080p hdtv+
    content_size:
      max: 5000
      strict: no
    include: [private/tvrss.yml]
    inputs:
      - html:
          url: https://thepiratebay.org/browse/208/{{i}}/3/0
          links_re: [magnet]
          title_from: url
          increment:
            from: 0
            to: 3
      - rss: https://rarbg.to/rssdd.php?category=18%3B41
    configure_series:
      settings:
        target: 720p-1080p hdtv+
      from:
        trakt_list:
          username: lvleph
          account: lvleph
          list: TV
          type: shows

  movies:
    trakt_lookup: yes
    proper_movies: yes
    content_size:
      max: 8000
      strict: no
    set:
      quality: dvdscr+
      target: 720p-1080p ac3+ h264+
      label: Movies
      path: /share/Public/Videos/To.Watch/Movies/
    include: [private/moviesrss.yml]
    inputs:
      - html:
          url: https://thepiratebay.org/browse/207/{{i}}/3/0
          links_re: [magnet]
          title_from: url
          increment:
            from: 0
            to: 3
      - rss: https://rarbg.to/rssdd.php?category=17%3B44
    list_match:
      from:
        - movie_list: MOVIES
      remove_on_match: yes
