#!/bin/sh

PROC=/opt/bin/flexget
CONFIG="/share/homes/erichlf/.flexget/config.yml"
ARGS="-c $CONFIG"

ACTION=$1

case $ACTION in
    start)
	ARGS="$ARGS daemon start -d"
        ;;
    stop )
	ARGS="daemon stop"
        ;;
    restart)
	ARGS="daemon restart"
        ;;
    status)
        ARGS="daemon status"
        ;;
    *)
        echo -e "Usage: $0 (start|stop|restart|status)"
        exit 1
        ;;
esac

$PROC $ARGS

#logger "Leaving ${0##*/}."
